CREATE TABLE clients (
    user_id TEXT PRIMARY KEY REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE psychologists (
    user_id TEXT PRIMARY KEY REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE CASCADE
);
