CREATE TABLE IF NOT EXISTS clients (
    user_id TEXT PRIMARY KEY REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS psychologists (
    user_id TEXT PRIMARY KEY REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS psychologist_clients (
    client_id TEXT REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE CASCADE,
    psycho_id TEXT REFERENCES "user"(id) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (client_id, psycho_id)
);
